import pytest
from juniorguru_chick.lib.intro import choose_intro_emojis, generate_intro_message


def test_choose_intro_emojis():
    message_content = """
        Mám takový obecný přehled o programování HTML, CSS,
        Bootstrap, Python, Matlab 🫣, SQL, okrajově JS.
    """

    assert '<:python:842331892091322389>' in choose_intro_emojis(message_content)


@pytest.mark.parametrize('message_content, expected_emoji', [
    ('základní struktury v pythonu a C# v ITnetwork', '<:csharp:842666113230045224>'),
    ('Láká mě C++ a C#', '<:cpp:842666129071931433>'),
])
def test_choose_intro_emoji_edge_cases(message_content, expected_emoji):
    assert expected_emoji in choose_intro_emojis(message_content)





@pytest.mark.asyncio  # unfortunately ui.View() touches the event loop
async def test_generate_intro_message_with_gh_connection_suggestion():
    message_content = """
        Mám takový obecný přehled o programování HTML, CSS,
        Bootstrap, Python, Matlab 🫣, SQL, okrajově JS.
        Můj Github je https://github.com/superghuser,
        ale pracuji teď na osobním projektu.
    """

    # TODO - update the snippet here and in the code.
    # omg, all of the instructions were generated by Co-pilot o.O
    gh_connection_snippet = """
        It looks like you've mentioned your GitHub profile in your intro message.
        Would you like to connect your GitHub account to your Discord account? This will allow you to get a special role and access to a private channel. So very fun!

        Here's how to do it:
        1. Go to Discord settings.
        2. Navigate to Connections.
        3. Click on GitHub.
        4. Authorize the connection.

        If you have any questions, feel free to ask in the #ahoj channel. We're here to help!
    """

    assert gh_connection_snippet in generate_intro_message(message_content)
