name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml
        cache: poetry
    - run: poetry install
    - run: poetry run pytest
    - if: ${{ github.ref == 'refs/heads/main' }}
      uses: superfly/flyctl-actions/setup-flyctl@master
    - if: ${{ github.ref == 'refs/heads/main' }}
      run: flyctl deploy
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
