name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - name: Install Python dependencies
        run: uv sync

      - name: Test
        run: uv run pytest

      - if: ${{ github.ref == 'refs/heads/main' }}
        uses: superfly/flyctl-actions/setup-flyctl@master

      - if: ${{ github.ref == 'refs/heads/main' }}
        run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
