name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: astral-sh/setup-uv@v7
    - run: uv run pytest
    - if: ${{ github.ref == 'refs/heads/main' }}
      uses: superfly/flyctl-actions/setup-flyctl@master
    - if: ${{ github.ref == 'refs/heads/main' }}
      run: flyctl deploy
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
